# Generated by Django 4.2.1 on 2023-05-27 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_id_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id_user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='conteudo',
            new_name='content',
        ),
    ]
