# Generated by Django 4.2.1 on 2023-05-26 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_id_user'),
        ('user', '0004_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
